-- Migration: Action Plans (Workflow Agent output)
-- Implements PAL_ARCHITECTURE.md §14, §40-42
-- Phase 3, Task 3.1: Workflow Agent (MeaningState → ActionPlan)

-- Action Plans table: stores validated workflow plans generated from meaning states
CREATE TABLE IF NOT EXISTS action_plans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- Domain identifiers
  plan_id TEXT NOT NULL UNIQUE,
  meaning_state_id TEXT NOT NULL,
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  
  -- Workflow representation
  workflow_ir JSONB NOT NULL,  -- Constrained WorkflowIR (nodes + edges)
  steps JSONB NOT NULL,         -- ActionStep[] with execution order
  
  -- Side effect classification
  side_effect_class TEXT NOT NULL CHECK (
    side_effect_class IN ('none', 'draft', 'external_write', 'financial', 'destructive')
  ),
  requires_approval BOOLEAN NOT NULL DEFAULT false,
  
  -- Provenance
  evidence_refs JSONB NOT NULL DEFAULT '[]',
  rationale_summary TEXT NOT NULL,
  
  -- Generation metadata
  generated_by_agent TEXT NOT NULL,
  generated_by_model TEXT NOT NULL,
  generated_by_version TEXT NOT NULL,
  
  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  
  -- Constraints
  CONSTRAINT plan_id_format CHECK (plan_id ~ '^plan_[a-zA-Z0-9_-]+$'),
  CONSTRAINT meaning_state_id_format CHECK (meaning_state_id ~ '^meaning_[a-zA-Z0-9_-]+$'),
  CONSTRAINT rationale_max_length CHECK (char_length(rationale_summary) <= 1000)
);

-- Indexes for query performance
CREATE INDEX idx_action_plans_workspace ON action_plans(workspace_id);
CREATE INDEX idx_action_plans_meaning_state ON action_plans(meaning_state_id);
CREATE INDEX idx_action_plans_side_effect ON action_plans(side_effect_class);
CREATE INDEX idx_action_plans_requires_approval ON action_plans(requires_approval);
CREATE INDEX idx_action_plans_created ON action_plans(created_at DESC);

-- Composite index for workspace + approval queries
CREATE INDEX idx_action_plans_workspace_approval ON action_plans(workspace_id, requires_approval);

-- RLS: Enable row-level security
ALTER TABLE action_plans ENABLE ROW LEVEL SECURITY;

-- RLS Policy: workspace members can read action plans
CREATE POLICY "workspace_members_read_action_plans"
ON action_plans
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM workspace_members wm
    WHERE wm.workspace_id = action_plans.workspace_id
      AND wm.user_id = auth.uid()
  )
);

-- RLS Policy: workspace members can insert action plans
CREATE POLICY "workspace_members_insert_action_plans"
ON action_plans
FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM workspace_members wm
    WHERE wm.workspace_id = action_plans.workspace_id
      AND wm.user_id = auth.uid()
  )
);

-- RLS Policy: workspace members cannot update or delete action plans
-- (action plans are immutable once created; new plans are created for modifications)

-- Comments
COMMENT ON TABLE action_plans IS 'Validated workflow plans generated by Workflow Agent from meaning states';
COMMENT ON COLUMN action_plans.plan_id IS 'Stable domain identifier for the action plan';
COMMENT ON COLUMN action_plans.meaning_state_id IS 'Parent meaning state that generated this plan';
COMMENT ON COLUMN action_plans.workflow_ir IS 'Constrained WorkflowIR with nodes and edges (PAL_ARCHITECTURE.md §21)';
COMMENT ON COLUMN action_plans.steps IS 'Ordered execution steps with capabilities and dependencies';
COMMENT ON COLUMN action_plans.side_effect_class IS 'Classification of external side effects';
COMMENT ON COLUMN action_plans.requires_approval IS 'Whether the plan requires human approval before execution';
COMMENT ON COLUMN action_plans.evidence_refs IS 'Provenance chain backing this plan';
COMMENT ON COLUMN action_plans.rationale_summary IS 'Human-readable explanation of the workflow plan';
