-- Migration: Action Proposals and Approval Decisions (Policy Engine output)
-- Implements PAL_ARCHITECTURE.md §15, §26-29, §40-42
-- Phase 3, Task 3.2: Policy Engine (ActionPlan → ActionProposal)

-- Action Proposals table: stores proposals generated by policy engine
CREATE TABLE IF NOT EXISTS action_proposals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- Domain identifiers
  proposal_id TEXT NOT NULL UNIQUE,
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  action_plan_id TEXT NOT NULL,
  
  -- Action details
  action_type TEXT NOT NULL,
  exact_payload JSONB NOT NULL,  -- Exact parameters to be executed
  destination TEXT,               -- Optional external destination
  recipient TEXT,                 -- Optional recipient
  scheduled_for TEXT,             -- Optional ISO-8601 scheduled time
  
  -- Risk and policy
  risk_class TEXT NOT NULL CHECK (
    risk_class IN ('read', 'draft', 'external_write', 'financial', 'destructive')
  ),
  evidence_refs JSONB NOT NULL DEFAULT '[]',
  policy_decision JSONB,          -- PolicyDecision from policy engine
  
  -- Lifecycle
  status TEXT NOT NULL CHECK (
    status IN ('pending', 'approved', 'edited', 'rejected', 'expired', 'executed', 'failed')
  ),
  version INTEGER NOT NULL DEFAULT 1,  -- For optimistic locking
  
  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ,         -- Optional expiry time (24h for pending)
  
  -- Constraints
  CONSTRAINT proposal_id_format CHECK (proposal_id ~ '^proposal_[a-zA-Z0-9_-]+$'),
  CONSTRAINT action_plan_id_format CHECK (action_plan_id ~ '^plan_[a-zA-Z0-9_-]+$'),
  CONSTRAINT version_positive CHECK (version > 0)
);

-- Approval Decisions table: stores human approval decisions
CREATE TABLE IF NOT EXISTS approval_decisions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- Domain identifiers
  decision_id TEXT NOT NULL UNIQUE,
  proposal_id TEXT NOT NULL,
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  proposal_version INTEGER NOT NULL,  -- Version of proposal when decision was made
  
  -- Decision details
  decision TEXT NOT NULL CHECK (decision IN ('approved', 'rejected', 'edited')),
  actor_id UUID NOT NULL,             -- User who made the decision
  reason TEXT NOT NULL,               -- Human-readable reason (max 500 chars)
  decided_at TIMESTAMPTZ NOT NULL,
  
  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  
  -- Constraints
  CONSTRAINT decision_id_format CHECK (decision_id ~ '^decision_[a-zA-Z0-9_-]+$'),
  CONSTRAINT proposal_id_fk_format CHECK (proposal_id ~ '^proposal_[a-zA-Z0-9_-]+$'),
  CONSTRAINT reason_length CHECK (char_length(reason) <= 500),
  
  -- Foreign key to proposals (soft reference - no FK constraint for flexibility)
  CONSTRAINT proposal_version_positive CHECK (proposal_version > 0)
);

-- Indexes for action_proposals
CREATE INDEX idx_action_proposals_workspace ON action_proposals(workspace_id);
CREATE INDEX idx_action_proposals_plan ON action_proposals(action_plan_id);
CREATE INDEX idx_action_proposals_status ON action_proposals(status);
CREATE INDEX idx_action_proposals_risk_class ON action_proposals(risk_class);
CREATE INDEX idx_action_proposals_created ON action_proposals(created_at DESC);
CREATE INDEX idx_action_proposals_expires ON action_proposals(expires_at) WHERE expires_at IS NOT NULL;

-- Composite indexes for common queries
CREATE INDEX idx_action_proposals_workspace_status ON action_proposals(workspace_id, status);
CREATE INDEX idx_action_proposals_workspace_pending ON action_proposals(workspace_id, status) WHERE status = 'pending';

-- Indexes for approval_decisions
CREATE INDEX idx_approval_decisions_proposal ON approval_decisions(proposal_id);
CREATE INDEX idx_approval_decisions_workspace ON approval_decisions(workspace_id);
CREATE INDEX idx_approval_decisions_actor ON approval_decisions(actor_id);
CREATE INDEX idx_approval_decisions_created ON approval_decisions(created_at DESC);

-- RLS: Enable row-level security
ALTER TABLE action_proposals ENABLE ROW LEVEL SECURITY;
ALTER TABLE approval_decisions ENABLE ROW LEVEL SECURITY;

-- RLS Policy: workspace members can read proposals
CREATE POLICY "workspace_members_read_proposals"
ON action_proposals
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM workspace_members wm
    WHERE wm.workspace_id = action_proposals.workspace_id
      AND wm.user_id = auth.uid()
  )
);

-- RLS Policy: workspace members can insert proposals
CREATE POLICY "workspace_members_insert_proposals"
ON action_proposals
FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM workspace_members wm
    WHERE wm.workspace_id = action_proposals.workspace_id
      AND wm.user_id = auth.uid()
  )
);

-- RLS Policy: workspace members can update proposals (for status changes)
CREATE POLICY "workspace_members_update_proposals"
ON action_proposals
FOR UPDATE
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM workspace_members wm
    WHERE wm.workspace_id = action_proposals.workspace_id
      AND wm.user_id = auth.uid()
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM workspace_members wm
    WHERE wm.workspace_id = action_proposals.workspace_id
      AND wm.user_id = auth.uid()
  )
);

-- RLS Policy: workspace members can read approval decisions
CREATE POLICY "workspace_members_read_decisions"
ON approval_decisions
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM workspace_members wm
    WHERE wm.workspace_id = approval_decisions.workspace_id
      AND wm.user_id = auth.uid()
  )
);

-- RLS Policy: workspace members can insert approval decisions
CREATE POLICY "workspace_members_insert_decisions"
ON approval_decisions
FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM workspace_members wm
    WHERE wm.workspace_id = approval_decisions.workspace_id
      AND wm.user_id = auth.uid()
  )
);

-- Comments
COMMENT ON TABLE action_proposals IS 'Proposals generated by policy engine from action plans';
COMMENT ON COLUMN action_proposals.proposal_id IS 'Stable domain identifier for the proposal';
COMMENT ON COLUMN action_proposals.action_plan_id IS 'Parent action plan';
COMMENT ON COLUMN action_proposals.exact_payload IS 'Exact parameters to be executed (PAL_ARCHITECTURE.md §29)';
COMMENT ON COLUMN action_proposals.risk_class IS 'Risk classification from policy engine';
COMMENT ON COLUMN action_proposals.policy_decision IS 'Deterministic policy decision (§26-27)';
COMMENT ON COLUMN action_proposals.status IS 'Proposal lifecycle status';
COMMENT ON COLUMN action_proposals.version IS 'Optimistic locking version for stale approval detection';
COMMENT ON COLUMN action_proposals.expires_at IS 'Expiry time for pending proposals (24h default)';

COMMENT ON TABLE approval_decisions IS 'Human approval decisions for action proposals';
COMMENT ON COLUMN approval_decisions.proposal_id IS 'Proposal being decided';
COMMENT ON COLUMN approval_decisions.proposal_version IS 'Version of proposal at decision time (for stale detection)';
COMMENT ON COLUMN approval_decisions.decision IS 'Approval outcome';
COMMENT ON COLUMN approval_decisions.actor_id IS 'User who made the decision';
COMMENT ON COLUMN approval_decisions.reason IS 'Human-readable decision rationale';
